compatibility_date = "2022-11-25"
name = "worker-template"
workers_dev = true
routes = []
vars = { }
main = "./dist/_worker.js"
port = 8787
kv_namespaces = [
  { binding = "store", id = "aaaaaaaaaaaaaa", preview_id = "bbbbbbbbbbb" }
]
[[r2_buckets]]
binding = 'bucket' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAMESPACE>'

[build]
command = "npm install && npm run build:api"
format = "modules"

[env.production]
workers_dev = false
vars = {  }


[env.local]
workers_dev = true
vars = { adminSecret = "adminSecret", ui = "localhost:3333" }

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8787
